# 

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_(self):
    self.driver.get("https://www.naver.com/")
    self.driver.set_window_size(800, 800)
    self.driver.find_element(By.ID, "query").click()
    self.driver.find_element(By.ID, "query").send_keys("주식")
    self.driver.find_element(By.ID, "query").send_keys(Keys.ENTER)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".csp dt > span").click()
    self.vars["win6888"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6888"])
    self.driver.find_element(By.LINK_TEXT, "3개월").click()
    self.driver.find_element(By.LINK_TEXT, "1년").click()
    self.driver.find_element(By.LINK_TEXT, "3년").click()
    self.driver.find_element(By.LINK_TEXT, "10년").click()
    self.driver.find_element(By.LINK_TEXT, "주봉").click()
    self.driver.find_element(By.LINK_TEXT, "월봉").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grp_nav > ul").click()
    self.driver.find_element(By.LINK_TEXT, "1일").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".nkindic_basic:nth-child(1) mark").click()
    self.vars["win2750"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2750"])
    self.driver.find_element(By.ID, "size_ct").click()
  
